import { useDisclosure } from '@mantine/hooks';
import {
  Drawer, Button, TextInput, Select, Stack, PasswordInput,
  Group, Text, Divider,
} from '@mantine/core';
import { IconPlus } from '@tabler/icons-react';
import useAddUsers from '../../../hooks/admin/UserManagement/useAddUsers';

/**
 * UC010 — Add User Drawer (opens from the RIGHT)
 * All class diagram variables: userName, userEmail, userPassword,
 * userPhone, userRole, isActive, preferenceID
 * userID is auto-generated by Firestore.
 */
const AddUsers = ({ onCreated }) => {
  const [opened, { open, close }] = useDisclosure(false);
  const { form, handleSubmit } = useAddUsers({ onCreated, onClose: close });

  return (
    <>
      <Button
        leftSection={<IconPlus size={16} />}
        color="olive"
        radius="xl"
        size="sm"
        onClick={open}
      >
        Add User
      </Button>

      <Drawer
        opened={opened}
        onClose={close}
        title="Add New User"
        position="right"
        size="md"
        padding="xl"
        styles={{
          title: { fontWeight: 800, fontSize: '18px', color: 'var(--mm-admin-sidebar)' },
          body: { overflowY: 'auto', height: 'calc(100vh - 60px)' },
        }}
      >
        <form onSubmit={form.onSubmit(handleSubmit)}>
          <Stack gap="md">
            {/* Identity */}
            <Text size="xs" c="dimmed" fw={700} tt="uppercase">Identity</Text>
            <TextInput
              label="User Name"
              placeholder="Full name"
              withAsterisk
              {...form.getInputProps('userName')}
            />
            <TextInput
              label="Email"
              placeholder="user@example.com"
              type="email"
              withAsterisk
              {...form.getInputProps('userEmail')}
            />
            <TextInput
              label="Phone Number"
              placeholder="+60123456789"
              {...form.getInputProps('userPhone')}
            />

            <Divider />

            {/* Security */}
            <Text size="xs" c="dimmed" fw={700} tt="uppercase">Security</Text>
            <PasswordInput
              label="Password"
              placeholder="Min. 8 characters"
              withAsterisk
              {...form.getInputProps('userPassword')}
            />

            <Divider />

            {/* Role & Status */}
            <Text size="xs" c="dimmed" fw={700} tt="uppercase">Role & Status</Text>
            <Select
              label="Role"
              withAsterisk
              data={[
                { value: 'user', label: 'User' },
                { value: 'admin', label: 'Admin' },
              ]}
              {...form.getInputProps('userRole')}
            />
            <Select
              label="Account Status"
              withAsterisk
              data={[
                { value: '0', label: '🟢 Active' },
                { value: '2', label: '🔴 Suspended' },
              ]}
              value={String(form.values.accountStatus)}
              onChange={(val) => form.setFieldValue('accountStatus', Number(val))}
            />

            <Divider />

            {/* Optional */}
            <Text size="xs" c="dimmed" fw={700} tt="uppercase">Optional</Text>
            <TextInput
              label="Preference ID"
              placeholder="Leave blank if not assigned"
              {...form.getInputProps('preferenceID')}
            />

            <Button type="submit" fullWidth mt="sm" color="olive" radius="xl">
              Create User
            </Button>
          </Stack>
        </form>
      </Drawer>
    </>
  );
};

export default AddUsers;
